<?php

/**
 * @file
 * Facturación GT module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function facturacion_gt_theme($existing, $type, $theme, $path) {
  return[
    'webform_facturar' => [
      'variables' => ['webform' => NULL],
      'template' => 'webform-facturar',
      'path' => 'modules/custom/facturacion_gt/templates'
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function facturacion_gt_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // formulario_feature()

  facturar_custom_composite($form, $form_state, $form_id);
  facturar_ajax($form, $form_state, $form_id);
  ingreso_stock_custom_composite($form, $form_state, $form_id);

}

/**
 * Funciones auxiliares del hook_form_alter().
 */
// Implementar campos para custom composite para productos en formulario de facturacion
function facturar_custom_composite(&$form, FormStateInterface $form_state, $form_id) {
  
  if ($form_id === 'webform_submission_facturar_add_form') {
    if (isset($form['elements']['productos_composite'])) {
      // Ocultar primer campo
      $fields['codigo_item'] = [
        '#display' => 'none'
      ];

      // Campos personalizados
      $fields['producto'] = [
        '#type' => 'entity_autocomplete',
        '#required' => true,
        '#weight' => 1,
        '#title' => 'Producto',
        '#placeholder' => 'Producto',
        '#target_type' => 'node',
        '#selection_handler' => 'default:node',
        '#selection_settings' => [
          'target_bundles' => [
            'producto' => 'producto'
          ],
          'sort' => [
            'field' => 'title',
            'direction' => 'ASC'
          ]
        ]
      ];
      
      $fields['precio'] = [
        '#type' => 'number',
        '#required' => false,
        '#weight' => 2,
        '#title' => 'Precio',
        '#placeholder' => 'Precio',
        '#readonly' => true
      ];

      $fields['cantidad'] = [
        '#type' => 'number',
        '#required' => true,
        '#weight' => 3,
        '#title' => 'Cantidad',
        '#placeholder' => 'Cantidad'
      ];
      
      $fields['subtotal'] = [
        '#type' => 'number',
        '#required' => false,
        '#weight' => 4,
        '#title' => 'Subtotal',
        '#placeholder' => 'Subtotal',
        '#readonly' => true
      ];

      $form['elements']['productos_composite']['#element'] = $fields;
    }
  }

}

// Autocompletar campos con ajax
function facturar_ajax(&$form, FormStateInterface $form_state, $form_id) {
  
  if ($form_id === 'webform_submission_facturar_add_form') {
    $form['#attached']['library'][] = 'facturacion_gt/facturar_webform_autofill';
  }

}

// Implementar campos para custom composite para productos en formulario de ingreso de stock
function ingreso_stock_custom_composite(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'webform_submission_ingreso_de_stock_add_form') {
    if (isset($form['elements']['productos'])) {
      // Ocultar primer campo
      $fields['hidden'] = [
        '#display' => 'none'
      ];

      // Campos personalizados
      $fields['producto'] = [
        '#type' => 'entity_autocomplete',
        '#required' => true,
        '#weight' => 0,
        '#title' => 'Producto',
        '#placeholder' => 'Producto',
        '#target_type' => 'node',
        '#selection_handler' => 'default:node',
        '#selection_settings' => [
          'target_bundles' => [
            'producto' => 'producto'
          ],
          'sort' => [
            'field' => 'title',
            'direction' => 'ASC'
          ]
        ]
      ];

      $fields['cantidad'] = [
        '#type' => 'number',
        '#required' => true,
        '#weight' => 1,
        '#title' => 'Cantidad',
        '#placeholder' => 'Cantidad'
      ];

      $form['elements']['productos']['#element'] = $fields;
    }
  }
}